
language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t heyleemhan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true heyleemhan/docker-react npm run test 